package respond

const (
	CODE_AUTH_HEADER_MISSING    = 1
	CODE_AUTH_TOKEN_INVALID     = 2
	CODE_INVALID_DATE_FORMAT    = 3
	CODE_INTERNAL_ERROR         = 4
	CODE_INVALID_JSON           = 5
	CODE_ALREADY_AT_FIRST_CHUNK = 6
	CODE_ALREADY_AT_LAST_CHUNK  = 7
)
