version: '3'

tasks:
  # helper to run on windows.
  # for some reason go build -o bot && ./bot doesn't work on windows.
  bot: 
    cmds:
      - go install
      - adhd-reader.exe
  
  test:
    cmds:
      - go test ./...